# Generated by Django 3.0.4 on 2020-03-27 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_remove_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logreg.users'),
            preserve_default=False,
        ),
    ]
