# Generated by Django 3.0.4 on 2020-03-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_articles_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='id',
            new_name='user',
        ),
    ]
